name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.26-alpine

    steps:
      # musl is recommended over glibc for CGO binaries
      - name: Install build dependencies
        run: |
          apk add --no-cache \
            gcc \
            musl-dev \
            git \
            sdl2-dev \
            sdl2-static \
            sdl2_image-dev \
            sdl2_image-static

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static binary
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64
          VERSION: ${{ github.ref_name }} # tag name as only runs on tags
        run: |
          go build \
            -ldflags="-s -w -linkmode external -extldflags -static -X main.version=$VERSION" \
            -o scrawl \
            .

      - name: Verify binary is statically linked
        run: |
          file scrawl
          ldd scrawl || true

      - name: Bundle with LICENSE
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir scrawl-linux-x86_64
          mv scrawl scrawl-linux-x86_64
          mv LICENSE scrawl-linux-x86_64
          tar -czf scrawl-linux-x86_64.tar.gz scrawl-linux-x86_64

      - name: Attach binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: scrawl-linux-x86_64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
